### ISSUE TITLE
Extension doesn't seems to work

### ISSUE THREAD

**Issue by Hax0rG1rl** [malerisch/burp-csj#11]
Hi, 

**Environment:** Kali Linux, Burp Pro 1.7.36, Java 1.8. Extension is loaded sucesfully. 

**Target:** a bitnami wordpress website just to replicate your video. 

**Issue**

When I send the requrest to the Crawler a new Firefox instance is started, stays there for a couple of seconds then it closes. The crawler says everything is okay and he is doing its job but it doesn't seems so. 

Can you confirm this extension actually still works with the latest Burp version or is a dead project? 

Thanks.

**Comment by malerisch** [comment]
hi there, thx for reaching out - unfortunately, this extension is based heavily on Crawljax and Selenium - in particular, Crawljax seems to be abandoned at the moment and this is why it is not working with the most recent browsers. To use this extension at the moment, you would need to use the same browser versions which were tested then.

**Comment by Hax0rG1rl** [comment]
Right. Thanks. I will close this one now.
